#!/usr/bin/env python
import argparse
import json
import urllib2

CONFIG_URL = ('https://raw.githubusercontent.com/mcomella/'
              'push-to-try-android/master/config.json')


def main():
    args = set_and_parse_args()
    syntax = get_syntax_from_server()
    if args.dry_run:
        print syntax
    else:
        pass  # TODO: call out to subprocess


def get_syntax_from_server():
    obj = json.load(urllib2.urlopen(CONFIG_URL))
    builds = ''.join(obj['builds'])  # No comma - can't explain that!
    platforms = ','.join(obj['platforms'])
    unit_suites = ','.join(obj['unit_suites'])
    talos_suites = ','.join(obj['talos_suites'])

    return ' '.join(['try:',
                     '-b', builds,
                     '-p', platforms,
                     '-u', unit_suites,
                     '-t', talos_suites])


def set_and_parse_args():
    p = argparse.ArgumentParser(description='TODO')
    p.add_argument('-d', '--dry-run', help='print try syntax; don\'t upload',
                   action='store_true')
    return p.parse_args()


if __name__ == '__main__':
    main()
